### ISSUE TITLE
Rol de ADMINISTRADOR BACKEND

### ISSUE THREAD

**Issue by Alegomcab1** [ISPP-LinkedPet/backend_isppet#63]
* Nuevo rol de administrador
- [x]   Banear / restringir usuarios
- [x]   Editar anuncios de la página
- [x]   Añadir veterinarios a la página
- [x]   Lista de veterinarios que han pagado
- [x]   Registrar protectoras
- [x]    Estadísticas básicas? (Ampliable)        
* Numero de publicaciones de crianzas
* Numero de publicaciones de adopciones
* Publicaciones rechazadas / total
* Publicaciones terminadas  / total
* Publicaciones en progreso  / total
